# Generated by Django 5.0.3 on 2024-03-14 16:44

import youtube_feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='link',
            field=models.CharField(validators=[youtube_feed.models.validate_playlist_link_contains_list_id]),
        ),
    ]
