# Generated by Django 5.0.3 on 2024-03-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_feed', '0003_alter_playlist_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
